name: Hola Mundo Test

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Check repositorio
        uses: actions/checkout@v4

      - name: Ejecutar test hola mundo
        run: node index.js

      - name: Notificacion ntfy
        run: |
          curl -H "Title: Nuevo Push en main" \
               -H "Priority: 2" \
               -H "Tags: github,devops" \
               -d "Se realizo el push al repositorio correctamente." \
               https://ntfy.sh/devops-itla
